version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: product-market
    ports:
        - "5432:5432"

  product-market:
    image: product-market
    depends_on:
      - db
    ports:
      - "8083:8083"
    restart: always

